# Generated by Django 3.0.5 on 2020-04-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.CharField(max_length=200, null=True)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fill_database.Speciality')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('site', models.CharField(max_length=200)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fill_database.Region')),
                ('specializations', models.ManyToManyField(through='fill_database.Specialization', to='fill_database.Speciality')),
            ],
        ),
        migrations.AddField(
            model_name='specialization',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fill_database.University'),
        ),
    ]
