# Generated by Django 3.0.5 on 2020-04-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill_database', '0003_auto_20200416_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
